import { hasPermission } from "@first-ai/auth";
import { EmptyState, inputClassName, PageHeader, secondaryButtonClassName, StatusBadge } from "@first-ai/ui";
import type { Metadata } from "next";
import Link from "next/link";

import { LeadControls, LeadForm } from "../../../components/forms";
import { withCrm } from "../../../lib/crm";
import { formatDate, formatMoney } from "../../../lib/format";

export const metadata: Metadata = { title: "Prospects" };
const PAGE_SIZE = 20;
const statuses = ["new","contacted","qualified","proposal","won","lost","archived"] as const;
export default async function LeadsPage({ searchParams }: { readonly searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  const params = await searchParams; const page=Math.max(Number.parseInt(params.page??"1",10)||1,1); const query=params.q?.trim(); const status=statuses.find(value=>value===params.status);
  const { rows, users, canWrite } = await withCrm(async ({context,leads})=>({ rows:await leads.searchLeads(context,{query,status,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE}), users:await leads.listAssignableUsers(context), canWrite:hasPermission(context.role,"leads.write") }));
  const names=new Map(users.map(user=>[user.id,`${user.firstName} ${user.lastName}`])); const href=(next:number)=>`/leads?${new URLSearchParams({...(query?{q:query}:{}),...(status?{status}:{}),page:String(next)})}`;
  return <div className="space-y-6"><PageHeader title="Prospects" description="Suivez les demandes et opportunités avant conversion."/><form role="search" className="grid gap-2 sm:grid-cols-[1fr_12rem_auto]"><label className="sr-only" htmlFor="lead-search">Rechercher</label><input id="lead-search" name="q" defaultValue={query} placeholder="Entreprise, nom, e-mail ou téléphone" className={inputClassName}/><select aria-label="Filtrer par statut" name="status" defaultValue={status??""} className={inputClassName}><option value="">Tous les statuts</option>{statuses.map(value=><option key={value} value={value}>{value}</option>)}</select><button className={secondaryButtonClassName}>Filtrer</button></form>{canWrite?<LeadForm/>:null}{rows.length===0?<EmptyState title="Aucun prospect" description={query||status?"Aucun prospect ne correspond aux filtres.":"Les nouveaux prospects apparaîtront ici."}/>:<div className="grid gap-3">{rows.map(lead=><article key={lead.id} className="rounded-2xl border border-neutral-200 bg-white p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-medium">{lead.companyName??[lead.firstName,lead.lastName].filter(Boolean).join(" ")}</h2><StatusBadge tone={lead.status==="new"?"blue":lead.status==="won"?"green":lead.status==="lost"?"red":"neutral"}>{lead.status}</StatusBadge></div><p className="mt-1 text-sm text-neutral-500">{lead.email??"—"} · {lead.phone??"—"}</p><p className="mt-2 text-xs text-neutral-400">{lead.source} · créé le {formatDate(lead.createdAt)} · {names.get(lead.assignedUserId??"")??"Non assigné"}</p></div><div className="shrink-0 text-left sm:text-right"><p className="font-medium">{formatMoney(lead.estimatedValue)}</p><p className="text-xs text-neutral-500">Score {lead.score}/100</p></div></div>{canWrite?<div className="mt-4 border-t border-neutral-100 pt-4"><LeadControls leadId={lead.id} status={lead.status} assignedUserId={lead.assignedUserId} users={users}/></div>:null}</article>)}</div>}<nav aria-label="Pagination prospects" className="flex justify-between"><span>{page>1?<Link href={href(page-1)} className={secondaryButtonClassName}>Précédent</Link>:null}</span>{rows.length===PAGE_SIZE?<Link href={href(page+1)} className={secondaryButtonClassName}>Suivant</Link>:null}</nav></div>;
}
