import { z } from "zod";

export const QUOTE_STATUSES = ["draft", "ready", "sent", "viewed", "accepted", "rejected", "expired", "cancelled"] as const;
export const JOB_STATUSES = ["draft", "scheduled", "confirmed", "en_route", "in_progress", "completed", "follow_up_required", "cancelled", "failed"] as const;
export const JOB_PRIORITIES = ["low", "normal", "high", "urgent"] as const;
export const INFESTATION_LEVELS = ["unknown", "low", "medium", "high", "critical"] as const;
const text = z.string().trim().min(1).max(5000);
const money = z.string().regex(/^\d{1,10}(\.\d{1,2})?$/, "Montant positif, avec deux décimales maximum.");
const quantity = z.string().regex(/^\d{1,6}(\.\d{1,3})?$/).refine(v => !/^0+(\.0+)?$/.test(v), "Quantité strictement positive.");
const taxRate = z.string().regex(/^\d{1,3}(\.\d{1,3})?$/).refine(v => Number(v) <= 100, "TVA comprise entre 0 et 100.");
const pagination = { query: z.string().trim().max(120).optional(), limit: z.number().int().min(1).max(100).default(20), offset: z.number().int().min(0).max(10000).default(0) };
export const createDraftQuoteSchema = z.strictObject({ customerId: z.uuid(), siteId: z.uuid(), validUntil: z.iso.date().optional(), notes: text.optional() });
export const updateDraftQuoteSchema = createDraftQuoteSchema.omit({ customerId: true, siteId: true }).partial();
export const quoteItemSchema = z.strictObject({ serviceId: z.uuid().nullable().optional(), description: text, quantity, unitPrice: money, taxRate, costEstimate: money.default("0"), sortOrder: z.number().int().min(0).max(200).default(0) });
export const addQuoteItemSchema = quoteItemSchema;
export const updateQuoteItemSchema = quoteItemSchema.partial();
export const searchQuotesSchema = z.strictObject({ ...pagination, status: z.enum(QUOTE_STATUSES).optional(), customerId: z.uuid().optional() });
export const acceptQuoteSchema = z.strictObject({ serviceId: z.uuid() });
export const createDraftJobSchema = z.strictObject({ customerId: z.uuid(), siteId: z.uuid(), serviceId: z.uuid(), description: text, priority: z.enum(JOB_PRIORITIES).default("normal"), infestationLevel: z.enum(INFESTATION_LEVELS).default("unknown"), price: money.default("0"), estimatedCost: money.default("0"), internalNotes: text.optional(), customerNotes: text.optional() });
export const scheduleJobSchema = z.strictObject({ scheduledStart: z.iso.datetime({ offset: true }), scheduledEnd: z.iso.datetime({ offset: true }) }).refine(v => Date.parse(v.scheduledEnd) > Date.parse(v.scheduledStart), { message: "La fin doit suivre le début.", path: ["scheduledEnd"] });
export const rescheduleJobSchema = scheduleJobSchema;
export const assignTechnicianSchema = z.strictObject({ assignedUserId: z.uuid().nullable() });
export const searchJobsSchema = z.strictObject({ ...pagination, status: z.enum(JOB_STATUSES).optional(), date: z.iso.date().optional(), customerId: z.uuid().optional() });
export const createJobReportSchema = z.strictObject({ jobId: z.uuid(), observations: text.optional() });
export const updateJobReportSchema = z.strictObject({ observations: text.optional(), infestationLevelBefore: z.enum(INFESTATION_LEVELS).optional(), infestationLevelAfter: z.enum(INFESTATION_LEVELS).optional(), treatmentPerformed: text.optional(), productsUsedSummary: text.optional(), recommendations: text.optional(), followUpRequired: z.boolean().optional(), followUpDate: z.iso.date().nullable().optional() });
export const followUpRecommendationSchema = z.strictObject({ followUpDate: z.iso.date() });
export type CreateDraftQuoteInput = z.infer<typeof createDraftQuoteSchema>;
export type QuoteItemInput = z.infer<typeof quoteItemSchema>;
export type CreateDraftJobInput = z.infer<typeof createDraftJobSchema>;
