import { expect, test } from "@playwright/test";
import { confirmInvoiceBusiness } from "./invoice-business";
import { e2eFixture } from "./fixture";

test("M1 billing configuration and explicit invoice classification are usable on mobile", async ({ page }) => {
  await page.goto("/login");
  await page.getByLabel("E-mail").fill(e2eFixture.email); await page.getByLabel("Mot de passe").fill(e2eFixture.password);
  await page.getByRole("button", { name: "Se connecter" }).click();
  await expect(page.getByRole("heading", { name: "Tableau de bord" })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/settings/billing");
  const seller = page.getByRole("form", { name: "Configurer le vendeur" });
  await expect(seller.getByLabel("Identité légale du vendeur")).toHaveValue("Vendeur Fictif Élodie — Œuvre");
  await seller.getByRole("button", { name: "Enregistrer l’identité vendeur" }).click();
  await expect(seller.getByRole("status")).toHaveText("Modification enregistrée.");
  await page.goto("/customers"); await page.getByRole("link", { name: new RegExp(e2eFixture.operationalCustomerName) }).click();
  await page.getByText("Configurer la facturation client", { exact: true }).click();
  const customer = page.getByRole("form", { name: "Enregistrer la facturation client" });
  await customer.getByLabel("Classification du client").selectOption("professional");
  await expect(customer.getByLabel("Adresse de facturation", { exact: true })).toHaveValue("2 Rue Facturation Fictive");
  await customer.getByRole("button", { name: "Enregistrer la facturation client" }).click();
  await expect(customer.getByRole("status")).toHaveText("Modification enregistrée.");
  await expect(page.getByRole("heading", { name: "Site Terrain Fictif" })).toBeVisible();
  await page.goto("/invoices"); await page.getByText("Nouvelle facture", { exact: true }).click();
  await page.getByLabel("Client", { exact: true }).selectOption({ label: e2eFixture.operationalCustomerName });
  await page.getByLabel("Échéance").fill("2026-11-05");
  await page.getByRole("button", { name: "Créer le brouillon" }).click();
  const add = page.getByRole("form", { name: "Ajouter une ligne" });
  await add.getByLabel("Description").fill("Prestation M1 fictive"); await add.getByLabel("Quantité").fill("1"); await add.getByLabel("Prix unitaire HT (€)").fill("10"); await add.getByLabel("TVA (%)").fill("20"); await add.getByRole("button", { name: "Ajouter la ligne" }).click();
  await expect(page.getByRole("region", { name: "Totaux" })).toContainText("12,00 €");
  const issue = page.getByRole("form", { name: "Émettre la facture" });
  await issue.getByLabel("Je confirme l’émission et le verrouillage des lignes").check(); await issue.getByRole("button").click();
  await expect(issue.getByRole("alert")).toContainText("classification fiscale explicite");
  const classification = page.getByRole("form", { name: "Enregistrer la classification" });
  await classification.getByLabel("Type de transaction").selectOption("B2B"); await classification.getByLabel("Nature des opérations").selectOption("services"); await classification.getByLabel("Territorialité fiscale").selectOption("domestic"); await classification.getByLabel("Traitement TVA de la facture").selectOption("normal");
  await classification.getByRole("button").click(); await expect(classification.getByRole("status")).toHaveText("Modification enregistrée.");
  await confirmInvoiceBusiness(page);
  await issue.getByLabel("Je confirme l’émission et le verrouillage des lignes").check(); await issue.getByRole("button").click();
  await expect(page.getByRole("link", { name: "Télécharger le PDF" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
