import { hasPermission } from "@first-ai/auth";
import { searchJobsSchema } from "@first-ai/schemas";
import { AuthorizationError } from "@first-ai/tools";
import { EmptyState, PageHeader, StatusBadge } from "@first-ai/ui";
import type { Metadata } from "next";
import Link from "next/link";
import { OperationalForm } from "../../../components/operational-form";
import { CustomerSelection, OperationalFilters, OperationalPagination } from "../../../components/operational-list";
import { withCrm } from "../../../lib/crm";
import { formatDateTime } from "../../../lib/format";
import { jobLabels, options, priorityLabels } from "../../../lib/operations";
export const metadata: Metadata = { title: "Interventions" };
export default async function JobsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string; date?: string; customerId?: string }> }) {
  const p = await searchParams, page = Math.min(501, Math.max(1, Number.parseInt(p.page ?? "1", 10) || 1));
  const parsed = searchJobsSchema.safeParse({ query: p.q || undefined, status: p.status || undefined, date: p.date || undefined, limit: 20, offset: (page - 1) * 20 });
  if (!parsed.success) return <EmptyState title="Filtres invalides" description="Vérifiez le statut ou la date demandée."/>;
  let data;
  try { data = await withCrm(async crm => { const timezone = await crm.jobs.getTimezone(crm.context); const canWrite = hasPermission(crm.context.role, "jobs.write"); const [rows, customers, sites, catalog] = await Promise.all([crm.jobs.searchJobs(crm.context, parsed.data), canWrite ? crm.customers.searchCustomers(crm.context, { limit: 100 }) : Promise.resolve([]), canWrite && p.customerId ? crm.sites.searchCustomerSites(crm.context, { customerId: p.customerId, limit: 100 }) : Promise.resolve([]), canWrite ? crm.catalog.listServices(crm.context, { limit: 100, active: true }) : Promise.resolve([])]); return { rows, timezone, canWrite, customers, sites, catalog }; }); } catch (e) { if (e instanceof AuthorizationError) return <EmptyState title="Accès non autorisé" description="Votre rôle ne permet pas de consulter les interventions."/>; throw e; }
  return <div className="space-y-6"><PageHeader title="Interventions" description="Planification et exécution terrain. Les techniciens ne voient que leurs affectations."/><OperationalFilters query={p.q} status={p.status} date={p.date} showDate labels={jobLabels}/>{data.canWrite ? <details open={Boolean(p.customerId)} className="rounded-2xl border border-neutral-200 bg-white p-5"><summary className="cursor-pointer font-medium">Nouvelle intervention</summary><div className="mt-5 space-y-5"><CustomerSelection customers={data.customers} value={p.customerId}/>{p.customerId && data.sites.length ? <OperationalForm operation="job.create" hidden={{ customerId: p.customerId }} submit="Créer l’intervention brouillon" fields={[{ name: "siteId", label: "Site", type: "select", required: true, options: data.sites.map(s => ({ value: s.id, label: s.name })) }, { name: "serviceId", label: "Prestation", type: "select", required: true, options: data.catalog.map(s => ({ value: s.id, label: s.name })) }, { name: "description", label: "Description", required: true }, { name: "priority", label: "Priorité", type: "select", value: "normal", options: options(priorityLabels) }, { name: "price", label: "Prix HT (€)", required: true, value: "0" }, { name: "estimatedCost", label: "Coût estimé (€)", required: true, value: "0" }]}/> : <p className="text-sm text-neutral-500">Choisissez un client disposant d’un site.</p>}</div></details> : null}{!data.rows.length ? <EmptyState title="Aucune intervention" description="Les interventions correspondant à votre recherche apparaîtront ici."/> : <div className="grid gap-3">{data.rows.map(({ job, customerName, siteName, serviceName, technicianFirstName, technicianLastName }) => <Link key={job.id} href={`/jobs/${job.id}`} className="grid gap-3 rounded-2xl border border-neutral-200 bg-white p-5 sm:grid-cols-3"><div><h2 className="font-semibold">{customerName}</h2><p className="text-sm text-neutral-600">{siteName} · {serviceName}</p></div><div className="text-sm"><p>{job.scheduledStart ? formatDateTime(job.scheduledStart, data.timezone) : "À planifier"}</p><p className="text-neutral-500">{[technicianFirstName, technicianLastName].filter(Boolean).join(" ") || "Non affectée"} · {priorityLabels[job.priority]}</p></div><div><StatusBadge>{jobLabels[job.status]}</StatusBadge></div></Link>)}</div>}<OperationalPagination route="/jobs" page={page} hasNext={data.rows.length === 20} params={{ q: p.q ?? "", status: p.status ?? "", date: p.date ?? "" }}/></div>;
}
