import { sql } from "drizzle-orm";
import { check, date, integer, jsonb, pgPolicy, pgTable, timestamp, unique, uuid, varchar } from "drizzle-orm/pg-core";
import type { FinancialRetentionPolicy } from "@first-ai/schemas";
import { organizations } from "./organizations.js";
const read = sql`organization_id = (select public.current_organization_id()) and exists (select 1 from public.users where auth_user_id = (select auth.uid()) and role in ('OWNER','ADMIN','MANAGER','ACCOUNTANT'))`;
export const financialRetentionPolicies = pgTable("financial_retention_policies", {
  organizationId: uuid("organization_id").primaryKey().references(() => organizations.id), closingMonth: integer("closing_month").notNull(), closingDay: integer("closing_day").notNull(), retentionYears: integer("retention_years").notNull(), version: integer("version").notNull().default(1), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, t => [check("financial_retention_policy_check", sql`${t.closingMonth} between 1 and 12 and ${t.closingDay} between 1 and 31 and ${t.retentionYears} between 10 and 50 and ${t.version} > 0`), pgPolicy("retention_policy_select_own", { for: "select", to: "authenticated", using: read })]).enableRLS();
export const financialArtifacts = pgTable("financial_artifacts", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), entityType: varchar("entity_type", { length: 16 }).notNull(), entityId: uuid("entity_id").notNull(), artifactType: varchar("artifact_type", { length: 24 }).notNull().default("original_issued_pdf"), documentNumber: varchar("document_number", { length: 32 }).notNull(), generatedAt: timestamp("generated_at", { withTimezone: true }).notNull(), sha256: varchar("sha256", { length: 64 }).notNull(), byteSize: integer("byte_size").notNull(), rendererVersion: varchar("renderer_version", { length: 64 }).notNull(), storageKey: varchar("storage_key", { length: 255 }).notNull(), policy: jsonb("policy").$type<(FinancialRetentionPolicy & { version: number }) | null>(), accountingClose: date("accounting_close"), retentionUntil: date("retention_until"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, t => [unique("financial_artifact_document_unique").on(t.organizationId, t.entityType, t.entityId), check("financial_artifact_check", sql`${t.entityType} in ('invoice','credit_note') and ${t.artifactType} = 'original_issued_pdf' and ${t.sha256} ~ '^[0-9a-f]{64}$' and ${t.byteSize} between 1 and 20971520 and ((${t.policy} is null and ${t.accountingClose} is null and ${t.retentionUntil} is null) or (${t.policy} is not null and ${t.accountingClose} is not null and ${t.retentionUntil} >= ${t.accountingClose}))`), pgPolicy("financial_artifact_select_own", { for: "select", to: "authenticated", using: sql`organization_id = (select public.current_organization_id()) and exists (select 1 from public.users where auth_user_id = (select auth.uid()) and role in ('OWNER','ADMIN','MANAGER','ACCOUNTANT','READ_ONLY'))` })]).enableRLS();
export const financialArchiveExports = pgTable("financial_archive_exports", {
  id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), sha256: varchar("sha256", { length: 64 }).notNull(), byteSize: integer("byte_size").notNull(), storageKey: varchar("storage_key", { length: 255 }).notNull(), periodFrom: date("period_from").notNull(), periodTo: date("period_to").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, t => [check("financial_export_check", sql`${t.periodFrom} <= ${t.periodTo} and ${t.sha256} ~ '^[0-9a-f]{64}$' and ${t.byteSize} between 1 and 104857600`), pgPolicy("financial_export_select_own", { for: "select", to: "authenticated", using: read })]).enableRLS();
