import { hasPermission } from "@first-ai/auth";
import { EmptyState, PageHeader, StatusBadge } from "@first-ai/ui";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { ContactForm, SiteForm } from "../../../../components/forms";
import { withCrm } from "../../../../lib/crm";

export const metadata: Metadata = { title: "Fiche client" };
export default async function CustomerPage({ params, searchParams }: { readonly params: Promise<{ id: string }>; readonly searchParams: Promise<{ created?: string }> }) {
  const { id } = await params; const notice = (await searchParams).created;
  let result;
  try { result = await withCrm(async ({ context, customers, contacts, sites }) => ({ customer: await customers.getCustomer(context,id), contacts: await contacts.searchContacts(context,{customerId:id,limit:100,offset:0}), sites: await sites.searchCustomerSites(context,{customerId:id,limit:100,offset:0}), canWriteContacts: hasPermission(context.role,"contacts.write"), canWriteSites: hasPermission(context.role,"sites.write") })); }
  catch (error) { if (typeof error === "object" && error !== null && "code" in error && error.code === "NOT_FOUND") notFound(); throw error; }
  const { customer, contacts, sites, canWriteContacts, canWriteSites } = result;
  return <div className="space-y-7">{notice ? <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Client créé avec succès.</p>:null}<PageHeader title={customer.name} description={customer.legalName ?? customer.type.replaceAll("_"," ")} action={<StatusBadge tone={customer.status==="active"?"green":"neutral"}>{customer.status}</StatusBadge>}/><section className="grid gap-3 sm:grid-cols-3"><Info label="Téléphone" value={customer.phone}/><Info label="E-mail facturation" value={customer.billingEmail}/><Info label="SIRET" value={customer.siret}/></section><section className="space-y-4"><h2 className="text-lg font-semibold">Contacts</h2>{canWriteContacts?<ContactForm customerId={customer.id}/>:null}{contacts.length===0?<EmptyState title="Aucun contact" description="Aucun contact n’est encore associé à ce client."/>:<div className="grid gap-3 sm:grid-cols-2">{contacts.map(contact=><article key={contact.id} className="rounded-2xl border border-neutral-200 bg-white p-4"><div className="flex justify-between gap-3"><h3 className="font-medium">{contact.firstName} {contact.lastName}</h3>{contact.isPrimary?<StatusBadge tone="blue">Principal</StatusBadge>:null}</div><p className="mt-1 text-sm text-neutral-500">{contact.role ?? "Fonction non renseignée"}</p><p className="mt-3 text-sm">{contact.phone ?? "—"} · {contact.email ?? "—"}</p></article>)}</div>}</section><section className="space-y-4"><h2 className="text-lg font-semibold">Sites</h2>{canWriteSites?<SiteForm customerId={customer.id} contacts={contacts}/>:null}{sites.length===0?<EmptyState title="Aucun site" description="Ajoutez un premier lieu d’intervention."/>:<div className="grid gap-3 sm:grid-cols-2">{sites.map(site=><article key={site.id} className="rounded-2xl border border-neutral-200 bg-white p-4"><h3 className="font-medium">{site.name}</h3><p className="mt-2 text-sm text-neutral-600">{site.addressLine1}<br/>{site.addressLine2?<>{site.addressLine2}<br/></>:null}{site.postalCode} {site.city} · {site.country}</p>{site.accessInstructions?<p className="mt-3 border-t border-neutral-100 pt-3 text-xs text-neutral-500">Accès : {site.accessInstructions}</p>:null}</article>)}</div>}</section></div>;
}
function Info({label,value}:{readonly label:string;readonly value:string|null}) { return <div className="rounded-2xl border border-neutral-200 bg-white p-4"><p className="text-xs font-medium uppercase tracking-wide text-neutral-400">{label}</p><p className="mt-2 text-sm font-medium">{value??"—"}</p></div>; }
