import { randomUUID } from "node:crypto";
import { hasPermission, type CurrentBusinessUser } from "@first-ai/auth";
import type { Job, JobReport, OperationalStoreInterface, Quote } from "@first-ai/database";
import { addQuoteItemSchema, createDraftQuoteSchema, scheduleJobSchema } from "@first-ai/schemas";
import { describe, expect, it, vi } from "vitest";
import { calculateQuoteTotals } from "./quote-calculation.js";
import { assertJobTransition, assertQuoteTransition, organizationDay } from "./operational-policies.js";
import { JobReportService, JobService, QuoteService } from "./operational-services.js";
import { createOperationalToolRegistry } from "./operational-tools.js";
const c: CurrentBusinessUser = { authUserId: randomUUID(), organizationId: randomUUID(), userId: randomUUID(), role: "OWNER" };
const id = randomUUID();
function store(): OperationalStoreInterface {
  const s: OperationalStoreInterface = {
    quotes: { get: vi.fn(), search: vi.fn(), create: vi.fn(), update: vi.fn(), items: vi.fn(async () => []), addItem: vi.fn(), updateItem: vi.fn(), removeItem: vi.fn(), countPending: vi.fn() },
    jobs: { get: vi.fn(), getByQuote: vi.fn(), search: vi.fn(), create: vi.fn(), update: vi.fn(), overlaps: vi.fn(async () => false), countToday: vi.fn() },
    reports: { get: vi.fn(), create: vi.fn(), update: vi.fn() },
    customerSite: vi.fn(async () => true), service: vi.fn(async () => true), technician: vi.fn(async () => true), listTechnicians: vi.fn(async () => []), timezone: vi.fn(async () => "Europe/Paris"), transaction: async operation => operation(s),
  }; return s;
}
const item = { quantity: "2", unitPrice: "100.10", taxRate: "20", costEstimate: "30" };
describe("deterministic quote arithmetic", () => {
  it("calculates HT, item VAT and margin excluding VAT", () => { expect(calculateQuoteTotals([item])).toEqual({ subtotal: "200.20", taxAmount: "40.04", total: "240.24", estimatedCost: "60.00", estimatedMargin: "140.20", estimatedMarginRate: "70.030" }); });
  it("supports mixed item VAT rates and fractional quantities", () => { expect(calculateQuoteTotals([{ ...item, quantity: "1.5", unitPrice: "10.01", taxRate: "5.5", costEstimate: "2.01" }, { ...item, quantity: "1", unitPrice: "100", taxRate: "0", costEstimate: "0" }])).toMatchObject({ subtotal: "115.02", taxAmount: "0.83", total: "115.85", estimatedCost: "3.02", estimatedMargin: "112.00" }); });
  it("rounds half cents per line, without floating-point errors", () => { expect(calculateQuoteTotals([{ ...item, quantity: "0.5", unitPrice: "0.01", costEstimate: "0", taxRate: "0" }]).subtotal).toBe("0.01"); });
  it("keeps negative margins and undefined zero-revenue rate explicit", () => { expect(calculateQuoteTotals([{ ...item, unitPrice: "0" }])).toMatchObject({ estimatedMargin: "-60.00", estimatedMarginRate: null }); expect(calculateQuoteTotals([]).total).toBe("0.00"); });
  it("rejects excessive amounts, invalid precision and invalid tax", () => { expect(() => calculateQuoteTotals([{ ...item, quantity: "999999", unitPrice: "9999999999.99" }])).toThrow(); expect(() => calculateQuoteTotals([{ ...item, unitPrice: "1.111" }])).toThrow(); expect(() => calculateQuoteTotals([{ ...item, taxRate: "101" }])).toThrow(); });
});
describe("operational validation and transitions", () => {
  it("rejects authoritative organization input and invalid item fields", () => { expect(createDraftQuoteSchema.safeParse({ customerId: id, siteId: id, organizationId: id }).success).toBe(false); expect(addQuoteItemSchema.safeParse({ ...item, quantity: "0", description: "Test" }).success).toBe(false); expect(scheduleJobSchema.safeParse({ scheduledStart: "2026-01-02T12:00:00Z", scheduledEnd: "2026-01-02T10:00:00Z" }).success).toBe(false); });
  it("allows explicit transitions and blocks terminal-state edits", () => { expect(() => assertQuoteTransition("draft", "ready")).not.toThrow(); expect(() => assertQuoteTransition("ready", "accepted")).not.toThrow(); expect(() => assertQuoteTransition("accepted", "draft")).toThrow(); expect(() => assertQuoteTransition("draft", "accepted")).toThrow(); expect(() => assertJobTransition("scheduled", "in_progress")).not.toThrow(); expect(() => assertJobTransition("completed", "in_progress")).toThrow(); expect(() => assertJobTransition("draft", "completed")).toThrow(); });
  it("resolves organization calendar days correctly across DST", () => { const spring = organizationDay("2026-03-29", "Europe/Paris"), autumn = organizationDay("2026-10-25", "Europe/Paris"); expect(spring.from.toISOString()).toBe("2026-03-28T23:00:00.000Z"); expect(spring.until.getTime() - spring.from.getTime()).toBe(23 * 3600000); expect(autumn.until.getTime() - autumn.from.getTime()).toBe(25 * 3600000); });
});
describe("operational service permissions, tenant scope and tools", () => {
  it.each(["OWNER", "ADMIN", "MANAGER"] as const)("%s can create drafts", async role => { const s = store(); await new QuoteService(s).createDraftQuote({ ...c, role }, { customerId: id, siteId: id }); expect(s.quotes.create).toHaveBeenCalledWith(c.organizationId, c.userId, { customerId: id, siteId: id }, expect.any(Number)); });
  it.each(["READ_ONLY", "TECHNICIAN", "ACCOUNTANT"] as const)("%s cannot mutate quotes or schedule", async role => { const s = store(); await expect(new QuoteService(s).createDraftQuote({ ...c, role }, { customerId: id, siteId: id })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(new JobService(s).scheduleJob({ ...c, role }, id, { scheduledStart: "2026-10-05T10:00:00Z", scheduledEnd: "2026-10-05T11:00:00Z" })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(s.quotes.create).not.toHaveBeenCalled(); });
  it("maps operational reads and own-report execution separately", () => { expect(hasPermission("TECHNICIAN", "quotes.read")).toBe(false); expect(hasPermission("TECHNICIAN", "jobs.read")).toBe(true); expect(hasPermission("TECHNICIAN", "job_reports.write")).toBe(true); expect(hasPermission("ACCOUNTANT", "quotes.read")).toBe(true); expect(hasPermission("ACCOUNTANT", "job_reports.write")).toBe(false); expect(hasPermission("READ_ONLY", "jobs.execute")).toBe(false); });
  it("scopes known UUID queries and technician searches", async () => { const s = store(); await expect(new QuoteService(s).getQuote(c, id)).rejects.toMatchObject({ code: "NOT_FOUND" }); expect(s.quotes.get).toHaveBeenCalledWith({ organizationId: c.organizationId, quoteId: id }); await new JobService(s).searchJobs({ ...c, role: "TECHNICIAN" }, {}); expect(s.jobs.search).toHaveBeenCalledWith(expect.objectContaining({ organizationId: c.organizationId, assignedUserId: c.userId, limit: 20, offset: 0 })); });
  it("a technician cannot access an unassigned job by UUID, start it, or write its report", async () => { const s = store(); vi.mocked(s.jobs.get).mockResolvedValue({ id, organizationId: c.organizationId, assignedUserId: randomUUID(), status: "scheduled" } as Job); const tech = { ...c, role: "TECHNICIAN" as const }; await expect(new JobService(s).getJob(tech, id)).rejects.toMatchObject({ code: "NOT_FOUND" }); await expect(new JobService(s).startJob(tech, id)).rejects.toMatchObject({ code: "NOT_FOUND" }); await expect(new JobReportService(s).createJobReportDraft(tech, { jobId: id })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("prevents item mutations after readiness", async () => { const s = store(); vi.mocked(s.quotes.get).mockResolvedValue({ status: "ready" } as Quote); await expect(new QuoteService(s).addQuoteItem(c, id, { ...item, description: "Fictional" })).rejects.toMatchObject({ code: "CONFLICT" }); expect(s.quotes.addItem).not.toHaveBeenCalled(); });
  it("requires a completed report before job completion", async () => { const s = store(); vi.mocked(s.jobs.get).mockResolvedValue({ status: "in_progress" } as Job); await expect(new JobService(s).completeJob(c, id)).rejects.toMatchObject({ code: "NOT_FOUND" }); expect(s.jobs.update).not.toHaveBeenCalled(); });
  it("a technician cannot edit another author's report even on an assigned job", async () => { const s = store(); vi.mocked(s.jobs.get).mockResolvedValue({ status: "in_progress", assignedUserId: c.userId } as Job); vi.mocked(s.reports.get).mockResolvedValue({ technicianId: randomUUID(), completedAt: null } as JobReport); await expect(new JobReportService(s).updateJobReport({ ...c, role: "TECHNICIAN" }, id, { observations: "Attempt" })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(s.reports.update).not.toHaveBeenCalled(); });
  it("requires observations/treatment and refuses edits to a completed report", async () => { const s = store(); vi.mocked(s.jobs.get).mockResolvedValue({ status: "in_progress" } as Job); vi.mocked(s.reports.get).mockResolvedValue({ technicianId: c.userId, observations: null, treatmentPerformed: null, completedAt: null } as JobReport); await expect(new JobReportService(s).completeJobReport(c, id)).rejects.toMatchObject({ code: "CONFLICT" }); vi.mocked(s.reports.get).mockResolvedValue({ completedAt: new Date() } as JobReport); await expect(new JobReportService(s).updateJobReport(c, id, { observations: "Attempt" })).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("calculates read-only totals without any persistence", async () => { const s = store(); vi.mocked(s.quotes.get).mockResolvedValue({ id } as Quote); await new QuoteService(s).calculateQuote(c, id); expect(s.quotes.update).not.toHaveBeenCalled(); });
  it("exposes only the required tools, reuses authorization and returns safe errors", async () => { const s = store(); const tools = createOperationalToolRegistry({ quotes: new QuoteService(s), jobs: new JobService(s), reports: new JobReportService(s) }); expect(Object.keys(tools)).toHaveLength(11); const result = await tools["quotes.createDraft"]!.execute({ ...c, role: "READ_ONLY", correlationId: id }, { customerId: id, siteId: id }); expect(result).toMatchObject({ success: false, error: { code: "FORBIDDEN" } }); expect(tools["quotes.calculateTotals"]!.risk).toBe(0); });
});
