"use client";

import { buttonClassName, FormField, inputClassName, secondaryButtonClassName } from "@first-ai/ui";
import { useActionState } from "react";

import {
  assignLeadAction,
  createContactAction,
  createCustomerAction,
  createLeadAction,
  createServiceAction,
  createSiteAction,
  updateLeadStatusAction,
  updateServiceAction,
  type ActionState,
} from "../app/actions";

const initialActionState: ActionState = { success: false };

function Message({ state }: { readonly state: ActionState }) { return state.message === undefined ? null : <p role="status" className={`rounded-xl px-3 py-2 text-sm ${state.success ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{state.message}</p>; }
function error(state: ActionState, field: string): string | undefined { return state.fieldErrors?.[field]?.[0]; }
function Submit({ children }: { readonly children: string }) { return <button className={buttonClassName} type="submit">{children}</button>; }
function Panel({ title, children }: { readonly title: string; readonly children: React.ReactNode }) { return <details className="rounded-2xl border border-neutral-200 bg-white"><summary className="cursor-pointer list-none px-4 py-3 text-sm font-medium marker:hidden">＋ {title}</summary><div className="border-t border-neutral-100 p-4">{children}</div></details>; }

export function CustomerForm() {
  const [state, action] = useActionState(createCustomerAction, initialActionState);
  return <Panel title="Nouveau client"><form action={action} className="grid gap-4 sm:grid-cols-2"><Message state={state}/><div className="hidden sm:block"/><FormField label="Type" name="type" error={error(state,"type")}><select id="type" name="type" className={inputClassName} defaultValue="company"><option value="company">Entreprise</option><option value="individual">Particulier</option><option value="property_manager">Syndic</option><option value="restaurant">Restaurant</option><option value="hotel">Hôtel</option><option value="retail">Commerce</option><option value="public">Public</option><option value="other">Autre</option></select></FormField><FormField label="Nom" name="name" error={error(state,"name")}><input id="name" name="name" required className={inputClassName}/></FormField><FormField label="Raison sociale" name="legalName" error={error(state,"legalName")}><input id="legalName" name="legalName" className={inputClassName}/></FormField><FormField label="SIRET" name="siret" error={error(state,"siret")}><input id="siret" name="siret" inputMode="numeric" className={inputClassName}/></FormField><FormField label="E-mail de facturation" name="billingEmail" error={error(state,"billingEmail")}><input id="billingEmail" name="billingEmail" type="email" className={inputClassName}/></FormField><FormField label="Téléphone" name="phone" error={error(state,"phone")}><input id="phone" name="phone" type="tel" className={inputClassName}/></FormField><FormField label="Délai de paiement (jours)" name="paymentTermsDays" error={error(state,"paymentTermsDays")}><input id="paymentTermsDays" name="paymentTermsDays" type="number" min="0" className={inputClassName}/></FormField><div/><div className="sm:col-span-2"><FormField label="Notes" name="notes" error={error(state,"notes")}><textarea id="notes" name="notes" rows={3} className={inputClassName}/></FormField></div><div className="sm:col-span-2"><Submit>Créer le client</Submit></div></form></Panel>;
}

export function ContactForm({ customerId }: { readonly customerId: string }) {
  const [state, action] = useActionState(createContactAction, initialActionState);
  return <Panel title="Ajouter un contact"><form action={action} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="customerId" value={customerId}/><div className="sm:col-span-2"><Message state={state}/></div><FormField label="Prénom" name="firstName" error={error(state,"firstName")}><input id="firstName" name="firstName" required className={inputClassName}/></FormField><FormField label="Nom" name="lastName" error={error(state,"lastName")}><input id="lastName" name="lastName" required className={inputClassName}/></FormField><FormField label="Fonction" name="role" error={error(state,"role")}><input id="role" name="role" className={inputClassName}/></FormField><FormField label="E-mail" name="email" error={error(state,"email")}><input id="email" name="email" type="email" className={inputClassName}/></FormField><FormField label="Téléphone" name="phone" error={error(state,"phone")}><input id="phone" name="phone" type="tel" className={inputClassName}/></FormField><label className="flex items-center gap-2 pt-7 text-sm"><input name="isPrimary" type="checkbox"/> Contact principal</label><div className="sm:col-span-2"><FormField label="Notes" name="notes" error={error(state,"notes")}><textarea id="notes" name="notes" rows={3} className={inputClassName}/></FormField></div><Submit>Ajouter le contact</Submit></form></Panel>;
}

export interface ContactOption { readonly id: string; readonly firstName: string; readonly lastName: string }
export function SiteForm({ customerId, contacts }: { readonly customerId: string; readonly contacts: readonly ContactOption[] }) {
  const [state, action] = useActionState(createSiteAction, initialActionState);
  return <Panel title="Ajouter un site"><form action={action} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="customerId" value={customerId}/><div className="sm:col-span-2"><Message state={state}/></div><FormField label="Nom du site" name="name" error={error(state,"name")}><input id="name" name="name" required className={inputClassName}/></FormField><FormField label="Contact principal" name="primaryContactId" error={error(state,"primaryContactId")}><select id="primaryContactId" name="primaryContactId" className={inputClassName}><option value="">Aucun</option>{contacts.map((contact)=><option key={contact.id} value={contact.id}>{contact.firstName} {contact.lastName}</option>)}</select></FormField><div className="sm:col-span-2"><FormField label="Adresse" name="addressLine1" error={error(state,"addressLine1")}><input id="addressLine1" name="addressLine1" required className={inputClassName}/></FormField></div><FormField label="Complément" name="addressLine2" error={error(state,"addressLine2")}><input id="addressLine2" name="addressLine2" className={inputClassName}/></FormField><FormField label="Code postal" name="postalCode" error={error(state,"postalCode")}><input id="postalCode" name="postalCode" required className={inputClassName}/></FormField><FormField label="Ville" name="city" error={error(state,"city")}><input id="city" name="city" required className={inputClassName}/></FormField><FormField label="Pays" name="country" error={error(state,"country")}><input id="country" name="country" defaultValue="FR" maxLength={2} className={inputClassName}/></FormField><FormField label="Instructions d’accès" name="accessInstructions" error={error(state,"accessInstructions")}><textarea id="accessInstructions" name="accessInstructions" rows={2} className={inputClassName}/></FormField><FormField label="Horaires d’accès" name="accessHours" error={error(state,"accessHours")}><textarea id="accessHours" name="accessHours" rows={2} className={inputClassName}/></FormField><div className="sm:col-span-2"><FormField label="Notes" name="notes" error={error(state,"notes")}><textarea id="notes" name="notes" rows={3} className={inputClassName}/></FormField></div><Submit>Ajouter le site</Submit></form></Panel>;
}

export function LeadForm() {
  const [state, action] = useActionState(createLeadAction, initialActionState);
  return <Panel title="Nouveau prospect"><form action={action} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="sm:col-span-2 lg:col-span-3"><Message state={state}/></div><FormField label="Source" name="source" error={error(state,"source")}><select id="source" name="source" className={inputClassName} defaultValue="manual">{["website","phone","google_ads","referral","outbound","tender","manual","other"].map(v=><option key={v} value={v}>{v}</option>)}</select></FormField><FormField label="Type" name="type" error={error(state,"type")}><input id="type" name="type" className={inputClassName}/></FormField><FormField label="Entreprise" name="companyName" error={error(state,"companyName")}><input id="companyName" name="companyName" className={inputClassName}/></FormField><FormField label="Prénom" name="firstName" error={error(state,"firstName")}><input id="firstName" name="firstName" className={inputClassName}/></FormField><FormField label="Nom" name="lastName" error={error(state,"lastName")}><input id="lastName" name="lastName" className={inputClassName}/></FormField><FormField label="E-mail" name="email" error={error(state,"email")}><input id="email" name="email" type="email" className={inputClassName}/></FormField><FormField label="Téléphone" name="phone" error={error(state,"phone")}><input id="phone" name="phone" type="tel" className={inputClassName}/></FormField><FormField label="Statut" name="status" error={error(state,"status")}><select id="status" name="status" defaultValue="new" className={inputClassName}>{["new","contacted","qualified","proposal","won","lost","archived"].map(v=><option key={v} value={v}>{v}</option>)}</select></FormField><FormField label="Score" name="score" error={error(state,"score")}><input id="score" name="score" type="number" min="0" max="100" defaultValue="0" className={inputClassName}/></FormField><FormField label="Valeur estimée (€)" name="estimatedValue" error={error(state,"estimatedValue")}><input id="estimatedValue" name="estimatedValue" inputMode="decimal" className={inputClassName}/></FormField><FormField label="Adresse" name="addressLine1" error={error(state,"addressLine1")}><input id="addressLine1" name="addressLine1" className={inputClassName}/></FormField><FormField label="Code postal" name="postalCode" error={error(state,"postalCode")}><input id="postalCode" name="postalCode" className={inputClassName}/></FormField><FormField label="Ville" name="city" error={error(state,"city")}><input id="city" name="city" className={inputClassName}/></FormField><div className="sm:col-span-2 lg:col-span-3"><FormField label="Notes" name="notes" error={error(state,"notes")}><textarea id="notes" name="notes" rows={3} className={inputClassName}/></FormField></div><Submit>Créer le prospect</Submit></form></Panel>;
}

export interface UserOption { readonly id: string; readonly firstName: string; readonly lastName: string }
export function LeadControls({ leadId, status, assignedUserId, users }: { readonly leadId: string; readonly status: string; readonly assignedUserId: string | null; readonly users: readonly UserOption[] }) {
  const [statusState, statusAction] = useActionState(updateLeadStatusAction, initialActionState); const [assignState, assignAction] = useActionState(assignLeadAction, initialActionState);
  return <div className="grid gap-2 sm:grid-cols-2"><form action={statusAction} className="flex gap-2"><input type="hidden" name="leadId" value={leadId}/><select aria-label="Statut" name="status" defaultValue={status} className={inputClassName}>{["new","contacted","qualified","proposal","won","lost","archived"].map(v=><option key={v} value={v}>{v}</option>)}</select><button className={secondaryButtonClassName}>OK</button></form><form action={assignAction} className="flex gap-2"><input type="hidden" name="leadId" value={leadId}/><select aria-label="Responsable" name="assignedUserId" defaultValue={assignedUserId ?? ""} className={inputClassName}><option value="">Non assigné</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</select><button className={secondaryButtonClassName}>OK</button></form><div className="sm:col-span-2"><Message state={statusState.success || statusState.message ? statusState : assignState}/></div></div>;
}

interface ServiceValues { readonly id?: string; readonly code?: string; readonly name?: string; readonly category?: string | null; readonly description?: string | null; readonly pricingMode?: string; readonly basePrice?: string | null; readonly estimatedDurationMinutes?: number | null; readonly active?: boolean }
export function ServiceForm({ values }: { readonly values?: ServiceValues }) {
  const action = values?.id === undefined ? createServiceAction : updateServiceAction; const [state, formAction] = useActionState(action, initialActionState);
  return <Panel title={values?.id === undefined ? "Nouvelle prestation" : `Modifier ${values.name ?? "la prestation"}`}><form action={formAction} className="grid gap-4 sm:grid-cols-2"><Message state={state}/><div className="hidden sm:block"/>{values?.id === undefined ? null : <input type="hidden" name="serviceId" value={values.id}/>}<FormField label="Code" name="code" error={error(state,"code")}><input id={`code-${values?.id ?? "new"}`} name="code" required defaultValue={values?.code} className={inputClassName}/></FormField><FormField label="Nom" name="name" error={error(state,"name")}><input id={`name-${values?.id ?? "new"}`} name="name" required defaultValue={values?.name} className={inputClassName}/></FormField><FormField label="Catégorie" name="category" error={error(state,"category")}><input id={`category-${values?.id ?? "new"}`} name="category" defaultValue={values?.category ?? ""} className={inputClassName}/></FormField><FormField label="Mode tarifaire" name="pricingMode" error={error(state,"pricingMode")}><select id={`pricing-${values?.id ?? "new"}`} name="pricingMode" defaultValue={values?.pricingMode ?? "fixed"} className={inputClassName}>{["fixed","hourly","unit","custom","subscription"].map(v=><option key={v} value={v}>{v}</option>)}</select></FormField><FormField label="Prix de base (€)" name="basePrice" error={error(state,"basePrice")}><input id={`price-${values?.id ?? "new"}`} name="basePrice" inputMode="decimal" defaultValue={values?.basePrice ?? ""} className={inputClassName}/></FormField><FormField label="Durée estimée (min)" name="estimatedDurationMinutes" error={error(state,"estimatedDurationMinutes")}><input id={`duration-${values?.id ?? "new"}`} name="estimatedDurationMinutes" type="number" min="1" defaultValue={values?.estimatedDurationMinutes ?? ""} className={inputClassName}/></FormField><div className="sm:col-span-2"><FormField label="Description" name="description" error={error(state,"description")}><textarea id={`description-${values?.id ?? "new"}`} name="description" rows={3} defaultValue={values?.description ?? ""} className={inputClassName}/></FormField></div><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={values?.active ?? true}/> Prestation active</label><div><Submit>{values?.id === undefined ? "Créer la prestation" : "Enregistrer"}</Submit></div></form></Panel>;
}
