import { hasPermission } from "@first-ai/auth";
import { AuthorizationError, ResourceNotFoundError, invoiceDocumentAvailability } from "@first-ai/tools";
import { EmptyState, PageHeader, StatusBadge } from "@first-ai/ui";
import Link from "next/link";
import { notFound } from "next/navigation";
import { z } from "zod";
import { randomUUID } from "node:crypto";
import { PAYMENT_METHODS } from "@first-ai/schemas";
import { OperationalForm } from "../../../../components/operational-form";
import { withCrm } from "../../../../lib/crm";
import { formatMoney, formatDateTime } from "../../../../lib/format";
import { invoiceItemFields, invoiceLabels } from "../../../../lib/invoices";
import { invoiceClassificationSchema } from "@first-ai/schemas";
import { billingFields } from "../../../../lib/billing-fields";
import { invoiceMentionFields } from "../../../../lib/invoice-mention-fields";
export const metadata = { title: "Détail facture" };
export default async function InvoicePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ paymentPage?: string }> }) {
  const { id } = await params; if (!z.uuid().safeParse(id).success) notFound();
  const query = await searchParams, page = Math.min(500, Math.max(1, Number(query.paymentPage) || 1));
  let data;
  try { data = await withCrm(async crm => ({ invoice: await crm.invoices.getInvoice(crm.context, id), creditPermissions: { read: hasPermission(crm.context.role, "creditNotes.read"), write: hasPermission(crm.context.role, "creditNotes.write") }, timezone: await crm.invoices.getTimezone(crm.context), payments: await crm.payments.listPayments(crm.context, id, { limit: 20, offset: (Math.floor(page) - 1) * 20 }), canRecord: hasPermission(crm.context.role, "payments.write"), canWrite: hasPermission(crm.context.role, "invoices.write"), canIssue: hasPermission(crm.context.role, "invoices.issue") })); }
  catch (e) { if (e instanceof ResourceNotFoundError) notFound(); if (e instanceof AuthorizationError) return <EmptyState title="Accès non autorisé" description="Votre rôle ne permet pas de consulter les factures."/>; throw e; }
  const i = data.invoice, editable = data.canWrite && i.status === "draft";
  const document = invoiceDocumentAvailability(i.documentSnapshot);
  const creditPermissions = data.creditPermissions;
  return <div className="space-y-6 break-words"><p className="text-sm text-neutral-500">{i.invoiceNumber ? "Numéro de facture" : "Référence brouillon"}</p><div className="break-all"><PageHeader title={i.invoiceNumber ?? i.draftReference} description={`${i.issueDate ? `Date d’émission : ${i.issueDate}` : "Date d’émission attribuée par le serveur à l’émission"} · Échéance : ${i.dueDate}`}/></div><StatusBadge>{invoiceLabels[i.status]}</StatusBadge>
    <div className="flex flex-wrap gap-4 text-sm underline"><Link href={`/customers/${i.customerId}`}>Client</Link>{i.quoteId ? <Link href={`/quotes/${i.quoteId}`}>Devis source</Link> : null}{i.jobId ? <Link href={`/jobs/${i.jobId}`}>Intervention source</Link> : null}</div>
    <section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Classification fiscale</h2><p className="text-sm text-neutral-500">Saisie explicite obligatoire avant émission. Aucune qualification automatique à partir du client, du site ou des taux.</p>{editable ? <OperationalForm operation="invoice.classify" hidden={{ invoiceId: id }} fields={billingFields(Object.keys(invoiceClassificationSchema.shape), i)} submit="Enregistrer la classification"/> : <p>{i.transactionType ?? "Historique non qualifié"} · {i.operationCategory ?? "Non renseignée"} · {i.vatTreatment ?? "Non renseigné"}</p>}<Link className="text-sm underline" href="/settings/billing">Configurer l’identité vendeur</Link></section>
    <section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Exécution et commande</h2><p className="text-sm text-neutral-500">Confirmez la date réelle ou la période achevée. Ni la création du brouillon, ni un paiement, ni une intervention liée ne fournissent automatiquement cette date. Les acomptes ne sont pas couverts.</p>{editable ? <OperationalForm operation="invoice.business" hidden={{ invoiceId: id }} fields={invoiceMentionFields("business", i.businessDetails, i.transactionType, i.operationCategory)} submit="Enregistrer les dates et références"/> : <p>{i.businessDetails?.executionDate ?? (i.businessDetails?.periodEnd ? `${i.businessDetails.periodStart} — ${i.businessDetails.periodEnd}` : "Historique non renseigné")}{i.businessDetails?.customerOrderReference ? ` · Commande : ${i.businessDetails.customerOrderReference}` : ""}</p>}</section>
    {i.issuedAt && document.available ? <a className="inline-flex rounded-xl bg-neutral-900 px-4 py-3 text-sm text-white focus-visible:outline-2 focus-visible:outline-offset-2" href={`/api/invoices/${id}/pdf`}>Télécharger le PDF</a> : i.status !== "draft" && i.status !== "cancelled" ? <p role="status" className="rounded-xl border p-4 text-sm">{document.message}</p> : null}
    <section className="space-y-3" aria-label="Lignes de facture">{i.items.map(item => <article key={item.id} className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="font-medium">{item.description}</h2><p className="text-sm">{item.quantity} × {formatMoney(item.unitPrice)} HT · TVA {item.taxRate} %</p>{editable ? <><details><summary className="cursor-pointer">Modifier la ligne</summary><OperationalForm operation="invoice.updateItem" hidden={{ invoiceId: id, itemId: item.id }} fields={invoiceItemFields(item)} submit="Enregistrer la ligne"/></details><OperationalForm operation="invoice.removeItem" hidden={{ invoiceId: id, itemId: item.id }} submit="Retirer la ligne"/></> : null}</article>)}{!i.items.length ? <EmptyState title="Aucune ligne" description="Ajoutez une ligne avant l’émission."/> : null}</section>
    {editable ? <div className="rounded-2xl border bg-white p-5"><OperationalForm title="Ajouter une ligne" operation="invoice.addItem" hidden={{ invoiceId: id }} fields={invoiceItemFields()} submit="Ajouter la ligne"/></div> : null}
    <section className="rounded-2xl border bg-white p-5" aria-label="Totaux"><h2 className="font-semibold">Totaux</h2><p>HT : {formatMoney(i.subtotal)}</p><p>TVA : {formatMoney(i.taxAmount)}</p><p className="font-semibold">TTC : {formatMoney(i.total)}</p></section>
    <section className="space-y-4 rounded-2xl border bg-white p-5" aria-label="Encaissements">
      <h2 className="font-semibold">Encaissements et corrections</h2><p>Reçu : {formatMoney(i.amountPaid)}</p><p>Avoirs émis : {formatMoney(i.amountCredited)}</p><p className="font-semibold">Reste à payer : {formatMoney(i.amountDue)}</p>{i.customerCredit !== "0.00" ? <p className="font-semibold">Crédit client : {formatMoney(i.customerCredit)} — aucun remboursement bancaire</p> : null}
      <p className="text-sm text-neutral-500">Saisie de fonds déjà reçus. Aucun paiement bancaire n’est déclenché.</p>
      {data.payments.map(p => <article key={p.id} className="space-y-2 rounded-xl border p-4"><p className="font-medium">{formatMoney(p.amount)} · {p.status === "completed" ? "Enregistré" : "Saisie annulée"}</p><p className="text-sm">{formatDateTime(p.paidAt, data.timezone)} · {methodLabels[p.method]}</p>{p.reference ? <p className="break-words text-sm">{p.reference}</p> : null}{p.cancellationReason ? <p className="break-words text-sm">Correction : {p.cancellationReason}</p> : null}{data.canRecord && p.status === "completed" ? <details><summary className="cursor-pointer text-sm">Corriger une saisie erronée</summary><OperationalForm operation="payment.cancel" hidden={{ invoiceId: id, paymentId: p.id }} fields={[{ name: "reason", label: "Motif de correction", required: true }]} submit="Annuler cette saisie"/></details> : null}</article>)}
      {!data.payments.length ? <p className="text-sm text-neutral-500">Aucun encaissement enregistré.</p> : null}
      <div className="flex justify-between text-sm">{page > 1 ? <Link href={`?paymentPage=${Math.floor(page) - 1}`}>Encaissements précédents</Link> : <span/>}{data.payments.length === 20 ? <Link href={`?paymentPage=${Math.floor(page) + 1}`}>Encaissements suivants</Link> : null}</div>
      {data.canRecord && ["issued", "sent", "overdue", "partially_paid"].includes(i.status) && i.amountDue !== "0.00" ? <OperationalForm title="Enregistrer un paiement" operation="payment.record" hidden={{ invoiceId: id, idempotencyKey: randomUUID() }} submit="Enregistrer l’encaissement" fields={[{ name: "amount", label: "Montant reçu (€)", required: true, help: "Décimales avec un point, exemple : 100.50" }, { name: "method", label: "Mode d’encaissement", type: "select", required: true, options: PAYMENT_METHODS.map(value => ({ value, label: methodLabels[value] })) }, { name: "paidAt", label: "Date de réception", type: "datetime-local", required: true }, { name: "reference", label: "Référence (facultative)" }]}/> : null}
    </section>
    {i.issuedAt && creditPermissions.read ? <section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Avoirs</h2><Link className="text-sm underline" href={`/credit-notes?invoice=${id}`}>Voir les avoirs de cette facture</Link>{creditPermissions.write && document.available && i.amountCredited !== i.total ? <details><summary className="cursor-pointer font-medium">Créer un avoir</summary><div className="mt-4"><OperationalForm operation="credit.create" hidden={{ invoiceId: id, idempotencyKey: randomUUID() }} submit="Créer le brouillon d’avoir" fields={[{ name: "correctionType", label: "Correction", type: "select", required: true, options: [{ value: "partial", label: "Partielle : choisir les montants HT" }, { value: "full", label: "Totale : toutes les bases restantes" }] }, { name: "reason", label: "Motif de correction", type: "textarea", required: true }]}/></div></details> : null}<p className="text-sm text-neutral-500">L’avoir corrige la dette sans modifier l’original ni les encaissements. Un crédit client n’est pas un remboursement.</p></section> : null}
    {i.notes ? <p className="whitespace-pre-wrap">{i.notes}</p> : null}
    {data.canIssue && i.status === "draft" ? <><p className="text-sm">L’émission attribue le numéro fiscal définitif et la date du jour dans le fuseau de l’organisation, puis fige le document commercial.</p><OperationalForm operation="invoice.issue" hidden={{ invoiceId: id }} submit="Émettre la facture" fields={[{ name: "confirmed", label: "Je confirme l’émission et le verrouillage des lignes", type: "checkbox", required: true }]}/></> : null}
    {editable ? <OperationalForm operation="invoice.cancel" hidden={{ invoiceId: id }} submit="Annuler le brouillon"/> : null}
    <p className="text-xs text-neutral-500">Le PDF utilise le numéro, la date, les identités et classifications figés à l’émission et un encart de solde actualisé. Aucun e-mail envoyé. Fondation technique : conformité fiscale non validée. Remboursements, archivage et transport électronique différés.</p></div>;
}
const methodLabels = { bank_transfer: "Virement reçu", card: "Carte", cash: "Espèces", cheque: "Chèque", other: "Autre" };
